export const ROUTES = {
    HOMESTACK: 'HomeStackScreen',
    AUTHSTACK: 'AuthStackScreen',
    ROOMSLIST: 'RoomsListScreem',
    AUTHENTICATIONSCREEN: 'AUTHENTICATIONSCREEN',
    RESETPASSWORD:'RESETPASSWORDSCREEN',
    REGISTER:'REGISTERSCREEN',
    REGULARLOGIN:'REGULARLOGINSCREEN',
    LOGIN:'LOGINSCREEN',
    PROJECTS:"PROJECTS_SCREEN",
    HOME:"HOME_SCREEN",
    BLOCAGE:"BLOCAGE_SCREEN",
    PROJECTINFO:"PROJECTINFO_SCREEN",
    ACTIVITY_REPORT:"ACTIVITY_REPORT_SCREEN",
    StaffMemberScreen:"StaffMember_SCREEN",
    PROJECT_LOCALISATION:"PROJECT_LOCALISATION_SCREEN",
    ETUDE_REPORT_SCREEN:"ETUDE_REPORT_SCREEN",
    STAFF_ACTIVITY_SCREEN:"STAFF_ACTIVITY_SCREEN",
    REJECT:"REJECT_SCREEN",
    WORK_TOOLS:"WORK_TOOLS_SCREEN",
    WORK_REPPORTS:"WORK_REPPORTS_SCREEN",
    AUTHORIZATION:"AUTHORIZATION_SCREEN",
    WORK_EDIT:"WORK_EDIT_SCREEN",
    CONSULTATION:"CONSULTATION_SCREEN"
  };

  export const SIMPLE_DATE_FORMAT='yyyy-MM-dd' 
  export const SIMPLE_DATE_TIME_FORMAT='yyyy-MM-dd HH:mm'
  export const SIMPLE_TIME_FORMAT ="HH:mm";

  export const ETUDE_STATUS={
    NON_DEMARRE:1,
    DEMARRE:2,
    EDITION_TSS:3,
    PRE_VALIDATION_TSS:4,
    VALIDATION_TSS:5,
    EDITION_APD:6,
    PRE_VALIDATION_APD:7,
    VALIDATION_APD:8,
    MAJ_TSS:9,
    MAJ_APD:10
  }
  export const AUTORISATION_STATUS={
    NON_DEMARRE:11,
  }

  export const DOC_TYPES={
    CROQUIS:"CROQUIS",
    APD:"APD",
    TSS_IMAGE:"TSS_IMAGE",
    BLOCAGE_IMG:"BLOCAGE_IMG",
    TRAVAUX_IMAGE:"TRAVAUX"
  }